### ISSUE TITLE
Running 'view' shows errors

### ISSUE THREAD

**Issue by purpleidea** [VundleVim/Vundle.vim#498]
I occasionally use the `view` command, which runs vim as readonly.

Problem:

```
Error detected while processing /home/james/.vim/vimrc:
line   11:
E492: Not an editor command: Plugin 'gmarik/Vundle.vim'
line   14:
E492: Not an editor command: Bundle 'croaky/vim-colors-github'
Press ENTER or type command to continue
```

**Comment by stefanlasiewski** [comment]
Hey folks, what about a good old conditional to handle this sort of problem?

```
" If we're not in vi-compatible mode, then load advanced VIM code
" like Bundles and colors
if !has("compatible")
  " Vundle code here
  call vundle#begin()
  Plugin 'gmarik/Vundle.vim'
  ... etc

  " Other non-vi code here

 """ End Vundle
endif
```

**Comment by stegr04** [comment]
Not sure if this will help anyone, but I figured I would put it out there since I recently experienced this problem. I was also using Vundle. Following Vundle's installation instructions I set my rtp. Except I had been messing around with my dot file/system structure pointing it to place that was valid until I moved it. Once I pointed it to the correct location (default as it turns out :)) the errors went away. I don't know if there is anyway for Vundle to not require setting rtp. But I wouldn't personally call my scenario a Vundle bug. I'm just glad it didn't take me too long to find it since I was focused for 5 minutes on where I might have set $MYVIMRC.

Cheers
