### ISSUE TITLE
Neovim support - undefined variable

### ISSUE THREAD

**Issue by PeterBocan** [VundleVim/Vundle.vim#632]
Hello guys, I'm having a big time with Vundle on Neovim (Installed via `brew install --HEAD neovim`)

    Error detected while processing function vundle#installer#new:
    line    1:
    E121: Undefined variable: a:1
    E15: Invalid expression: (a:1 == '') ? g:bundles : map(copy(a:000), 'vundle#config#bundle(v:val, {})')
 
Any ideas how to fix this issue?

**Comment by PeterBocan** [comment]
I'm running on OS X 10.10.3 and this issue was invoked with "PluginInstall".

**Comment by nfischer** [comment]
Are you sure the Vundle plugin is up to date? I found a line similar to the one referenced in the error output, but it's in an old version. Not sure why neovim can't handle that line while vim apparently was able to, but this might fix the issue:
$ cd ~/.vim
$ cd bundle/Vundle.vim || cd bundle/vundle/
$ git status # make sure there are no local changes, otherwise please revert them
$ git pull origin master

If you're curious where the code was changed, it looks like this commit did it:
https://github.com/VundleVim/Vundle.vim/commit/1df432aecfc0dacd93a1da0938830206f418fd66

Did these steps help at all?

**Comment by PeterBocan** [comment]
I've used a hack:
       
      call vundle#begin("~/.nvim/bundle")

And it works like a charm... maybe it's conflicting with Vim and/or directories are messed up.

**Comment by nfischer** [comment]
Is your install of vundle out of date? I'm confused as to why you would be seeing that line of code, since that's been changed in recent versions. Do you have vundle installed somewhere else on your system?

**Comment by PeterBocan** [comment]
Well, it might be the case, because I didn't update Vundle in a longer period of time...

**Comment by nfischer** [comment]
I would check your install of Vundle (change to the directory and run `git status` to make sure there are no local changes and then run `git pull origin master` to update). If you still have the same issue, then there must be something weird going on. It looks like you may need to call `vundle#begin()` anyway, although I'd have to dig through the source more to be completely sure.

**Comment by PeterBocan** [comment]
Well, Neovim is running properly, and I'm can't check the version of the Vundle from Vim directory because I've already updated it.
