### ISSUE TITLE
Error installing vimrc

### ISSUE THREAD

**Issue by rainiscold** [VundleVim/Vundle.vim#637]
Hello all,

I was customizing vim, got this error while trying to update bundles. 

Anyone knows what is going on?

Thanks,

![screen shot 2015-08-19 at 11 11 06 am](https://cloud.githubusercontent.com/assets/13358884/9361866/1edab9bc-4663-11e5-9f58-8ee3c527ffee.png)

**Comment by ryanoasis** [comment]
seems like its not finding vundle. can you paste a link to your `vimrc` or paste it (if it's short)

these links may help you:

http://stackoverflow.com/questions/25444680/unknown-function-vundlebegin
http://stackoverflow.com/questions/12179655/vundle-for-vim-is-not-working-on-ubuntu

**Comment by rainiscold** [comment]
here is the link of the vimrc that I use

https://github.com/johntfoster/dotvim/blob/master/vimrc

**Comment by rainiscold** [comment]
I did this and it didn't work for me.


...........................................................
set rtp+=~/.vim/bundle/Vundle.vim
to

set rtp+=/home/[YourUserName]/.vim/bundle/Vundle.vim   //do not use ~

**Comment by nfischer** [comment]
I think I know the issue. If you have `Plugin 'gmarik/vundle`, then vundle installs in a directory called `.vim/bundle/vundle/`, not the preferred `.vim/bundle/Vundle.vim/`.

Solution:
Change `Plugin 'gmarik/vundle'` to be `Plugin 'VundleVim/Vundle.vim'` inside your vimrc. If you can't get vim to work for you (it still should though), we'll forgive you for using nano this one time.
Next, try this out:
```
$ cd ~/.vim/bundle/ # If this doesn't exist, make this directory
$ git clone https://github.com/VundleVim/Vundle.vim.git
```

Any other errors are likely specific to the plugins you're using, since I did these steps and got it to work using a small subset of your plugins (didn't want to download ALL of them after all)

Happy vimming!

**Comment by ryanoasis** [comment]
@rainiscold did the suggestion work for you? We're you ever able to solve this?

**Comment by wsdjeg** [comment]
@rainiscold  i have checked you vimrc,please change `Plugin 'gmarik/vundle'`to `Plugin 'VundleVim/Vundle.vim'`and put this after the line `call vundle#begin()`,it is better to put this first of your plugin list!

**Comment by wsdjeg** [comment]
also you need to change `set rtp+=~/.vim/bundle/vundle`to`set rtp+=~/.vim/bundle/Vundle.vim`
here is example
```vim
set nocompatible
syntax on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
filetype plugin indent on
```

**Comment by ryanoasis** [comment]
@rainiscold did you try what @wsdjeg proposed and were you able to solve?

**Comment by rainiscold** [comment]
@wsdjeg Thank you for your suggestion. I appreciated.

**Comment by rainiscold** [comment]
@ryanoasis  Someone helped me with that. Sorry for the late response.

**Comment by ryanoasis** [comment]
No problem, thanks :+1:
