### ISSUE TITLE
 fatal: repository 'https://github.com/user/L9.git/' not found  

### ISSUE THREAD

**Issue by leiminglin** [VundleVim/Vundle.vim#686]
fatal: repository 'https://github.com/user/L9.git/' not found

**Comment by wsdjeg** [comment]
here is what you want 
https://github.com/VundleVim/Vundle.vim/blob/master/README_ZH_CN.md

**Comment by wsdjeg** [comment]
any response?
there is no Plugin named user/L9，the picture in the readme ,is just tell you how to intsall plugin .

**Comment by nfischer** [comment]
I think the README should be updated here. I've seen a few people that put user/L9 in their vimrc. It's nice to have that as an example, but I think the example needs to be better documented, since so many people "just want it to work" and will copy-paste the examples from the README without thinking.

**Comment by wsdjeg** [comment]
ok,I will send a PR to make the readme "works" better

**Comment by wsdjeg** [comment]
@nfischer how about this PR, just use a fork of `L9`

**Comment by nfischer** [comment]
@wsdjeg that's definitely much better! Thanks! I left a couple comments over there, but either way, it's definitely an improvement

**Comment by leiminglin** [comment]
:+1:

**Comment by ryanoasis** [comment]
Closing since #692 has been merged in since.

Reopen if there is more needed on this.
