### ISSUE TITLE
Suggestion: Option to run "git checkout master" before "git pull" during PluginUpdate

### ISSUE THREAD

**Issue by LiquidityC** [VundleVim/Vundle.vim#694]
I have my dotfiles in git with vim plugins added as submodules.
When checking out a project with submodules exact commits are checked out and not the master branch on the submodules.
It would be nice if there was an option in vundle to run "git checkout master" before running "git pull" when running ":PluginUpdate" because I don't think I'm the first person to have dotfiles in a repo.

I think I'll try to implement this one myself but I've got little experience with vimscript so it might take a while.

**Comment by nfischer** [comment]
The solution I use is to ignore my bundle folder. Cloning my dotfiles installs without installing my dependencies (aka vim plugins). For that part, I just run PluginInstall

Submodules are nice because git will install your dependencies for you, and you're guaranteed that they won't update to an incompatible version. But if you're using a package manager like Vundle, I think you lose those benefits anyway

**Comment by LiquidityC** [comment]
Yeah perhaps. I think it was "reverting from broken master branches" that was the main benefit. That and some configuration that was done post install for some plugins. Come to think of it that might not be the case any longer so this might not be a giant issue for me anymore.
I still don't think the suggestion is horrible though :D

**Comment by nfischer** [comment]
I certainly don't think it's a horrible suggestion. You might have better like trying to get this as a feature in @Shougo's [neobundle](https://github.com/Shougo/neobundle.vim) (if it's not already present), since I think that project aims to have a larger feature set.

I just thought I'd share my way of doing things, in case you preferred to stick with Vundle. For reference, here's my [vimfiles](https://github.com/nfischer/vimfiles) in case anyone else is curious how to set this up.
