### ISSUE TITLE
where to config plugin settings is recommended?

### ISSUE THREAD

**Issue by dragonxlwang** [VundleVim/Vundle.vim#705]
I'm sure this must be already discussed somewhere but I did tried to find it without a satisfying answer...

I know that we should put settings for plugins outside ``call vundle#begin()`` / ``call vundle#end() `` (because using #rc instead would cause longer time to load?). 

But for those settings, is there a way to test if a plugin is already loaded or not. This is helpful in cases where I comment out ``Plugin XXX`` early and thus I don't want the settings for XXX to be loaded anymore.

Any suggestion is greatly helpful.

**Comment by nfischer** [comment]
@dragonxlwang 

> because using #rc instead would cause longer time to load?

Yeah, you'll get better performance (vim starts up faster) from `begin` and `end`. Use `rc` if you prefer. I use a lot of plugins, so I like `begin` and `end`.

> But for those settings, is there a way to test if a plugin is already loaded or not. This is helpful in cases where I comment out Plugin XXX early and thus I don't want the settings for XXX to be loaded anymore.

What kinds of settings are you talking about? Here's some examples from plugins that I use:

 1. [vim-pydocstring](https://github.com/heavenshell/vim-pydocstring) has an optional variable `g:pydocstring_enable_mapping`. I decide to set this option (and [here's where I do](https://github.com/nfischer/vimfiles/blob/master/vimrc#L92)). If I comment out that `Plugin` line, leaving the variable config line is harmless.
 2. [fugitive](https://github.com/tpope/vim-fugitive) is another example. I like to use it [with mappings](https://github.com/nfischer/vimfiles/blob/master/vimrc#L121-L134). If I comment out the `Plugin` line, the mappings still persist. This is harmless until I invoke them. When I do that, vim complains `E492: Not an editor command: Gstatus`. It's just a message though, not harmful.

I think case 1 is harmless, so I'll assume you're concerned with case 2 or with some other case (feel free to post the config you're actually talking about). **For case 2**, it'd be great if I could wrap my fugitive mappings in a block that says "if `:Gstatus` is a command, run this block, otherwise don't." Unfortunately, as [this post](http://stackoverflow.com/a/5010399) points out, this doesn't work. Perhaps there's an option in Vundle to make it work like this, but I suspect there's performance tradeoffs that make it less preferable.

Here's a **workaround** I've considered using, though:

```vimL
Plugin 'tpope/fugitive' | let s:fugitive_loaded = 1;
" ...
if exists('s:fugitive_loaded')
  " fugitive specific stuff here
endif
```

Putting a comment in front of `Plugin` does the trick for you. `|` lets you write 2 statements on one line. `s:` is the script-scope prefix (scope is your whole vimrc file, but not exposed to the user). `exists()` checks if that variable exists.

**Comment by ryanoasis** [comment]
Nothing specific to Vundle if I am understanding your question correctly.

However most plugins usually follow the convention of providing a global scoped variable to detect whether or not a plugin has been loaded, for example: `g:loaded_nerd_tree`, `g:loaded_gundo`.

---

@nfischer You beat me to it with a lot better answer but I will still post just in case :+1: :laughing:

**Comment by dragonxlwang** [comment]
> Here's a workaround I've considered using, though:

> Plugin 'tpope/fugitive' | let s:fugitive_loaded = 1;
" ...
if exists('s:fugitive_loaded')
  " fugitive specific stuff here
endif

This seems to be a elegant way to deal my problem until vundle can comeup with something to test if realtime path of that package is added or not...

A million thanks for @nfischer's detailed insight.

**Comment by nfischer** [comment]
> A million thanks for @nfischer's detailed insight.

My pleasure! Glad I could help :+1:

> You beat me to it with a lot better answer but I will still post just in case :+1: :laughing:

@ryanoasis That's also a great answer! I didn't actually know that plugins provided variables like that. That's probably an even cleaner way to do it for the plugins that expose those variables.

**Comment by ryanoasis** [comment]
Closing for now as solved
