### ISSUE TITLE
Can't install Vundle in Windows Subsystem for Linux (Ubuntu OS)

### ISSUE THREAD

**Issue by sus007** [VundleVim/Vundle.vim#829]
### My _.vimrc_ file: 
[vimrc.txt](https://github.com/VundleVim/Vundle.vim/files/1213380/vimrc.txt)
# The errors I got while opening Vim through bash:
![image](https://user-images.githubusercontent.com/7630815/29150542-ef1716aa-7d9a-11e7-9f8d-50e48819650f.png)

## Could you help me configure the **.vimrc** file properly ?

**Comment by mudongliang** [comment]
https://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it

**Comment by sus007** [comment]
@mudongliang I couldn't follow up with the instructions on that link, could you clarify the issue with my case yourself ? As far as I can tell, it's the issue with the _spacing/indentation_ in my **.vimrc** file contents. As I followed your site, one page led to another and I was left with at least 10, not 15 tabs on my browser. Hence, being a Linux novice I'm not being able to interpret the **Vim** filesystem & format, so your help would be humbly appreciated. 🙏

**Comment by TheFirstDeity** [comment]
@sus007 The ^M thing is an extra hidden character that Windows uses for its line endings, and Linux doesn't like them. It was most likely caused by a Windows program modifying your `.vimrc` and thereby confusing Linux. The link @mudongliang sent with the `:/s` deletion _should_ work... But I never found carriage-returns that way, and there's a simple fix using `vim`.

1. Open your messed up file in `vim`
2. Type ':' (to input command) and say `set ff=unix`
3. Save your repaired file with ':w' and you're good to go

- To find out why this works, run `vim` and check out `:help ff` or `:h fileformat`.

Try to avoid touching your Linux with Windows binaries, it'll mess everything up.

You **can** use Linux programs to modify Windows files (that's safe because Linux sees a "fake" driver that knows how to talk to Windows) but it doesn't work the other way around. Linux can touch Windows stuff, but Windows will break Linux stuff.

So maybe you opened `.vimrc` in notepad, or accidentally ran a Windows tool on your Ubuntu files. That can happen when WSL picks up a Windows binary from $PATH with an identical name. You can test by saying `which npm` (for example) and it'll tell you the binary/script it would run.

**Comment by sus007** [comment]
@TheFirstDeity I appreciate your help mate, thanks a lot. I simply had to edit my .vimrc file via Vim in stead of Notepad to fire up my Vundle. I better close this issue now.

**Comment by DanEdens** [comment]
This was useful, Thanks
