### ISSUE TITLE
E492: Not an editor command: PluginInstall

### ISSUE THREAD

**Issue by AidanDai** [VundleVim/Vundle.vim#863]
I have a error `E492: Not an editor command: PluginInstall`, please help me!

these reference are no effective.

https://github.com/VundleVim/Vundle.vim/issues/486

https://github.com/VundleVim/Vundle.vim/wiki/Common-Issues

https://stackoverflow.com/questions/30017366/vim-error-e492-not-an-editor-command-plugininstall/30017967

vim version:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)

config:

this is my config: https://github.com/AidanDai/vim

**Comment by davidlowryduda** [comment]
I see that you're trying to install everything from a script. If you open your .vimrc and directly run :PluginInstall, what happens?

**Comment by jkuzmanovik** [comment]
Same Error..Any Solutions??

**Comment by davidlowryduda** [comment]
@jkuzmanovik Are you saying that you have also run the same install script and you have trouble? That would seem sort of remarkable. Or are you really saying just that `:PluginInstall` doesn't seem to work for you? If it's the latter, then you should say what steps you've followed from the installation and your setup.

**Comment by AidanDai** [comment]
@davidlowryduda show error: `E492: Not an editor command: PluginInstall`

**Comment by davidlowryduda** [comment]
@AidanDai Your config's install.sh is a bit confusing. You create `./bundle`, remove Vundle if it's there, and then clone Vundle to `~/.vim/bundle/`. Note that there is no reason to suspect that the place you cloned Vundle has anything to do with the `./bundle` directory you created earlier, unless you are disciplined in running this script from a particular place.

Then you try to  `rm $HOME/.vim` directory, even though this will fail since you have just cloned Vundle there (unless you have default settings on rm to remove non-empty directories, or if your $HOME/.vim is not the same as ~/.vim).

Finally you symlink ~/.vim to a $FOLDER. This symlink should fail, since the previous step shouldn't have removed `~/.vim` since it's not empty. But if for some reason it doesn't fail, then you've deleted Vundle you just cloned!

There are a lot of things playing against each other in your small install.sh file. It would be much more straightforward if you followed the install instructions here directly first. You can then organize that into an install.sh script if you want.

**Comment by AidanDai** [comment]
@davidlowryduda thank you very much, I was thinking.

**Comment by angelbeibei** [comment]
@AidanDai 
Can you tell me how you solved this problem?
 Thanks

**Comment by davidlowryduda** [comment]
@angelbeibei The problem in this issue appears (to me) to be more strongly related to the install script that AidanDai was using and less related to vundle itself. If you use the same install script, then that is one thing. But if you followed a different installation setup, then you should describe what you have done.

**Comment by AidanDai** [comment]
@angelbeibei checlk your install step.

reference: https://github.com/VundleVim/Vundle.vim/issues/863#issuecomment-381417609
