### ISSUE TITLE
Vim: Warning: Output is not to a terminal

### ISSUE THREAD

**Issue by fanux** [VundleVim/Vundle.vim#896]
I want install it in docker, so I using dockerfile to build it.
```
...
RUN yum install -y vim && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim && 	vim +PluginInstall +qall
```
it output:
```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```
How can I fix this, I think this is caused by interaction during building

**Comment by davidlowryduda** [comment]
These are both generic vim messages, not vundle specific. Presumably the warnings come from the `vim +PluginInstall +qall` part, as this is when vim itself is called. I'm not too familiar with what exactly docker does during initial build, but I find the `Input is not from a terminal` warning to be a bit surprising.

Nonetheless, since you don't interact with either input or output, presumably these warnings don't matter.

You might try using `vim -es +PluginInstall +qall` instead, which starts vim in EX mode, silently.

**Comment by fanux** [comment]
`vim -es +PluginInstall +qall` returned a non-zero code: 1 ...

**Comment by fanux** [comment]
Yes cant interact during docker build, and vim  +PluginInstall +qall  this command need input `Enter` to continue. Interact is evil....

**Comment by fanux** [comment]
why vim always prompt me this? Can I close this prompt?
```
➜  ~ vim

--- Autocommands ---
Press ENTER or type command to continue
```

**Comment by davidlowryduda** [comment]
It appears there is something fundamentally different about your setup. `vim +PluginInstall +qall` is not interactive for me (and it works just fine).

I'm not sure what you mean when you say that vim always prompts you. Are you saying you get prompted to hit `ENTER` when you just normally open vim? If so, then this indicates there is something odd happening in your configuration, probably in your .vimrc.

I also realize now that you didn't mention setting up a .vimrc in your dockerbuild. Presumably you get one from somewhere? It's necessary to add vundle to vim's runtimepath, which is what the lines at the top of the vimrc in the README refer to.

**Comment by fanux** [comment]
```
set nocompatible              " be iMproved, required
" 🔑  (key)
let mapleader=","
filetype off "required

set foldmethod=indent

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Plugin 'nsf/gocode',{'rtp':'vim/'}
Plugin 'fatih/vim-go'
Bundle 'scrooloose/nerdtree'
"Bundle 'cespare/vim-golang'
" Bundle 'dgryski/vim-godef'
Plugin 'Valloric/YouCompleteMe'
" Plugin 'SirVer/ultisnips'
" Plugin 'majutsushi/tagbar'
Plugin 'vim-scripts/taglist.vim'
" Plugin 'junegunn/vim-emoji'
" Plugin 'rjohnsondev/vim-compiler-go'
" Plugin 'dgryski/vim-godef'
" Plugin 'davidhalter/jedi-vim'
" Plugin 'scrooloose/syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
nmap <C-h> <C-w>h
nmap <C-l> <C-w>l
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k

" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
map <C-n> :NERDTreeToggle<CR>
map <C-t> :b 1 <CR>


Bundle 'majutsushi/tagbar'
nmap <Leader>t :TagbarToggle<CR>
let g:tagbar_width = 25
autocmd VimEnter * nested :call tagbar#autoopen(1)
autocmd BufWritePre *.go:Fmt
let g:tagbar_right = 1
let g:Tlist_Ctags_Cmd='/usr/local/Cellar/ctags/5.8_1/bin/ctags'

"let g:tagbar_type_go = {
"    \ 'ctagstype' : 'go',
"    \ 'kinds'     : [
"        \ 'p:package',
"        \ 'i:imports:1',
"        \ 'c:constants',
"        \ 'v:variables',
"        \ 't:types',
"        \ 'n:interfaces',
"        \ 'w:fields',
"        \ 'e:embedded',
"        \ 'm:methods',
"        \ 'r:constructor',
"        \ 'f:functions'
"    \ ],
"    \ 'sro' : '.',
"    \ 'kind2scope' : {
"        \ 't' : 'ctype',
"        \ 'n' : 'ntype'
"    \ },
"    \ 'scope2kind' : {
"        \ 'ctype' : 't',
"        \ 'ntype' : 'n'
"    \ },
"    \ 'ctagsbin'  : 'gotags',
"    \ 'ctagsargs' : '-sort -silent'
"    \ }

let g:molokai_original = 1
let g:rehash256 = 1
set sw=4

colorscheme molokai

set nu
set ts=4
set expandtab
syntax on

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }

let g:UltiSnipsExpandTrigger="<C-g>"

"godef
"will open the definition in a new tab
let g:godef_split=2
let g:godef_same_file_in_same_window=1

au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>T <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)

au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)

"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim
autocmd BufWritePost,FileWritePost *.go execute 'Lint' | cwindow
"
"if emoji#available()
"  let g:gitgutter_sign_added = emoji#for('small_blue_diamond')
"   let g:gitgutter_sign_modified = emoji#for('small_orange_diamond')
"   let g:gitgutter_sign_removed = emoji#for('small_red_triangle')
"   let g:gitgutter_sign_modified_removed = emoji#for('collision')
" endif
"e
set completefunc=emoji#complete
map <C-e> :%s/:\([^:]\+\):/\=emoji#for(submatch(1), submatch(0))/g <CR>

set lines=120 columns=150
```
This is my .vimrc file

**Comment by davidlowryduda** [comment]
Indeed, you should receive errors on first open with this vimrc. One source that will cause errors is the line `autocmd VimEnter * nested :call tagbar#autoopen(1)`. Another is the line `colorscheme molokai`.

If you start with this vimrc, clone and place vundle, and then call `vim +PluginInstall +qall`, then the following steps will happen

1. vim opens
2. VimEnter autocommands are resolved
3. vim attempts to call `tagbar#autoopen(1)`, but
4. vim hasn't yet installed tagbar, so this throws an error E117 for an unknown function
5. vim reports the error and prompts for continuation

There may be other functions that you're calling before they're defined, aside from tagbar and the colorscheme, but these are the first two that I noticed when testing your configuration. Of course, after initial installation these errors will disappear, since these functions (and colorscheme) will be defined.

One way to resolve this would be to have a minimal previmrc that just contains the initial vundle declarations.

A slightly different way which I think should work (but which is perhaps a bit inelegant) would be to write a script file `install.vimscript` that looks like

```
(empty line)
:PluginInstall
(empty line)
:qa!
(empty line)
```

except with actual empty lines on those lines. Then you can call `vim -s install.vimscript` to run the script. The first empty line feeds the return to eat the initial error, and the rest is pretty self-explanatory (and where I put in a few extra empty lines).

**Comment by fanux** [comment]
Thanks a lot. I delete `VimEnter * nested :call tagbar#autoopen(1)` and `colorscheme molokai` and vim also prompt me.   I build vim from source,  confused...

**Comment by davidlowryduda** [comment]
Building vim from source isn't the source of your trouble.

I noted `tagbar#autoopen` and `colorscheme molokai` only because there were the first two lines that I noticed caused errors on first installation. There are more, but I didn't note them since they aren't vundle errors. I'll give you a brief note on how you can find them --- start from a clean state (no `.vim/` or `.vimrc`) and go through your steps individually. These are the steps you first mentioned in this issue: acquiring (or building) vim, making a vimrc, cloning vundle, and trying to install vundle.

But do this by hand. You'll see for yourself if vim throws an error. If it does, fix your error and try again. For example, doing this with your original vimrc throws errors concerning your colorscheme and commands not existing.

Good luck!

**Comment by fanux** [comment]
Thank you, I will try this. I install vim plugins in docker and commit container as  image, fix my problem by hand. I close this issue now.
