### ISSUE TITLE
Plugins Not Loading and Weird (?) Behavior on Install Preview

### ISSUE THREAD

**Issue by jonathan-alvaro** [VundleVim/Vundle.vim#907]
I'm on Ubuntu 18.04 right now and my problem is that whenever i call `:PluginInstall`, Vundle shows me the preview with all the plugins working. But, as soon as I type `:bdelete` or `:q`, then all the plugins mysteriously unloads. Another oddity that I noticed was that in the preview buffer, I can only use `j` and `k` to navigate whereas `h` and `l` are overrode for help and HelpTags(?) respectively. Here is my `.vimrc` file:

```
set ignorecase
set nocompatible
set hlsearch

" Required settings for Vundle
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" badwolf color-scheme
Plugin 'sjl/badwolf'

" prettifies bottom status bar
Plugin 'itchyny/lightline.vim'

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on    " required

" Changes color scheme to badwolf
colo badwolf
```

**Comment by davidlowryduda** [comment]
What do you mean when you say that the plugins unload?

**Comment by jonathan-alvaro** [comment]
So, when I typed in the `:PluginInstall` command, it displays a preview buffer of changes in plugins. When the buffer still exists, all the plugins that I installed are still active. For example, I installed the `badwolf` color scheme and another plugin for the status bar (which name I forgot and I don't have access to my laptop atm. Will check soon). When the preview buffer still exists, the status bar plugin got applied. But, as soon as I type `:bdelete` or `:q` and closed the preview buffer, `vim` goes back to vanilla without any plugins.

**Comment by davidlowryduda** [comment]
The expected behavior is for no changes to occur until the next time you start vim and source the .vimrc again. You can check whether the plugins have been installed to the correct location by examining your (by default) `~/.vim/bundle` directory and checking that there is a directory for each installed plugin. For instance, you might check that the directory `~/.vim/bundle/badwolf` or `~/.vim/bundle/vim-airline` (if you use airline) exists.

**Comment by jonathan-alvaro** [comment]
Yes, I have ensured that directories for both plugins exist and there are files within them. I have also tried restarting both my vim and my terminal and yet both of them still doesn't load on start. Also, the plugin that i use is `lightline`

**Comment by davidlowryduda** [comment]
This indicates that vundle successfully cloned and installed the plugins. You might check that they're added to the correct rtp by trying to access their documentation. For instance, you might try `:h vundle` or `:h lightline`. You can also test whether the colorscheme is recognized by trying `:colo badwolf` in a running vim.

**Comment by jonathan-alvaro** [comment]
Sorry for the late reply. From what I tried, `:h lightline` and `:colo badwolf` does work which indicates that the rtp is indeed correct(?). But they are still not getting loaded automatically. Even worse for `lightline`, I don't know how to start it at all, unlike `badwolf`.

**Comment by davidlowryduda** [comment]
There is good news and bad news. The good news is that it appears that vundle has successfully installed the plugins and integrated their documentation. It appears that vundle has done everything it is supposed to do --- this should be exactly the same as though you manually installed these plugins. The question now is why your colorscheme isn't being set correctly in your vimrc. (I know nothing about lightlight, so I can't comment on it).

One possibility is that some setting elsewhere is overriding your colorscheme choice. This could occur later in your vimrc (where I'm assuming that you only posted a simplified vimrc above), or elsewhere in your vim configuration if you have a more exotic setup. Debugging colorschemes can be a pain, since really they're just a collection of highlight commands.

But I think that we can probably figure it out. One idea might be to see where a few highlight groups were last set. For instance, running `:verbose hi vimcomment` or `verbose hi folded` will indicate where these highlight groups were set.

**Comment by jonathan-alvaro** [comment]
Just to make sure, do I need to put `:colo badwolf` in order to use the colorscheme or should it be loaded automatically?

**Comment by davidlowryduda** [comment]
If you set `colorscheme badwolf` in your vimrc (and there is no later colorscheme that overrides it), then it should happen automatically when you start vim.

**Comment by jonathan-alvaro** [comment]
Ah, I see, the problem is that I didn't put `colo badwolf` into the `vimrc`. The `lightline` problem is similar too. Thanks for the help @davidlowryduda
